services:
  web:
    container_name: web
    image: remusengo/drf_project
    command: sh -c "python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - app:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

    env_file:
      - ./.env

  nginx:
    image: remusengo/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  db:
    container_name: db
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
#    ports:
#      - "5432:5432"
    env_file:
      - ./.env
    healthcheck: # Проверка работоспособности
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    container_name: redis
    image: redis:7.4
    expose:
      - "6379"
#    ports:
#      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - ./.env
    command: redis-server --save 60 1 --loglevel warning

  celery_worker:
    container_name: celery_worker
    image: remusengo/drf_project
    command: celery -A config worker --loglevel info
    volumes:
      - app:/app
    env_file: "./.env"
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    container_name: celery_beat
    image: remusengo/drf_project
    command: celery -A config beat --loglevel info
    env_file:
      - ./.env
    volumes:
      - app:/app
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
  static_volume:
  redis_data:
  app:
